services:
  postgres:
    image: bitnami/postgresql:14
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: forum
    volumes:
      - postgres_data:/bitnami/postgresql

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - '3333:3333'
    environment:
      DATABASE_URL: postgresql://docker:docker@postgres:5432/forum?schema=public
      JWT_SECRET: your-secret-key-here
      NODE_ENV: production
    depends_on:
      - postgres

volumes:
  postgres_data:
