/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Forum API
 * Forum API with DDD + Clean Architecture
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from './client';
export interface User {
  id: string;
  name: string;
  email: string;
  role: string;
  createdAt: string;
}

export interface Question {
  id: string;
  slug: string;
  title: string;
  content: string;
  authorId: string;
  authorName: string;
  answersCount?: number;
  createdAt: string;
  updatedAt?: string;
}

export interface QuestionDetail {
  id: string;
  slug: string;
  title: string;
  content: string;
  authorId: string;
  authorName: string;
  /** @nullable */
  bestAnswerId?: string | null;
  createdAt: string;
  updatedAt?: string;
}

export interface Answer {
  id: string;
  content: string;
  authorId: string;
  authorName: string;
  isBestAnswer?: boolean;
  createdAt: string;
}

export interface QuestionsResponse {
  questions?: Question[];
  total?: number;
  page?: number;
  perPage?: number;
}

export interface AnswersResponse {
  answers?: Answer[];
  total?: number;
  page?: number;
  perPage?: number;
}

export type PostRegisterBodyRole = typeof PostRegisterBodyRole[keyof typeof PostRegisterBodyRole];


export const PostRegisterBodyRole = {
  STUDENT: 'STUDENT',
  INSTRUCTOR: 'INSTRUCTOR',
} as const;

export type PostRegisterBody = {
  name: string;
  email: string;
  /** @minLength 6 */
  password: string;
  role?: PostRegisterBodyRole;
};

export type PostRegister201 = {
  user?: User;
};

export type PostSessionsBody = {
  email: string;
  password: string;
};

export type PostSessions200 = {
  user?: User;
};

export type GetMe200 = {
  user?: User;
};

export type GetQuestionsParams = {
page?: number;
};

export type PostQuestionsBody = {
  title: string;
  content: string;
  attachmentsIds?: string[];
};

export type PostQuestions201 = {
  question?: Question;
};

export type GetQuestionsPopularParams = {
page?: number;
};

export type GetQuestionsSearchParams = {
q: string;
tags?: string;
page?: number;
};

export type GetQuestionsSlug200 = {
  question?: QuestionDetail;
};

export type PutQuestionsQuestionIdBody = {
  title: string;
  content: string;
  attachmentsIds?: string[];
};

export type PutQuestionsQuestionId200 = {
  question?: Question;
};

export type GetQuestionsQuestionIdAnswersParams = {
page?: number;
};

export type PostQuestionsQuestionIdAnswersBody = {
  content: string;
  attachmentsIds?: string[];
};

export type PutAnswersAnswerIdBody = {
  content: string;
  attachmentsIds?: string[];
};

export type GetQuestionsQuestionIdCommentsParams = {
page?: number;
};

export type PostQuestionsQuestionIdCommentsBody = {
  content: string;
};

export type PostAnswersAnswerIdCommentsBody = {
  content: string;
};

export type GetHealth200 = {
  status?: string;
};

/**
 * @summary Register a new user
 */
export const postRegister = (
    postRegisterBody: PostRegisterBody,
 signal?: AbortSignal
) => {


      return customInstance<PostRegister201>(
      {url: `/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postRegisterBody, signal
    },
      );
    }



export const getPostRegisterMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postRegister>>, TError,{data: PostRegisterBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postRegister>>, TError,{data: PostRegisterBody}, TContext> => {

const mutationKey = ['postRegister'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postRegister>>, {data: PostRegisterBody}> = (props) => {
          const {data} = props ?? {};

          return  postRegister(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postRegister>>>
    export type PostRegisterMutationBody = PostRegisterBody
    export type PostRegisterMutationError = void

    /**
 * @summary Register a new user
 */
export const usePostRegister = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postRegister>>, TError,{data: PostRegisterBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postRegister>>,
        TError,
        {data: PostRegisterBody},
        TContext
      > => {
      return useMutation(getPostRegisterMutationOptions(options), queryClient);
    }

/**
 * @summary Authenticate a user
 */
export const postSessions = (
    postSessionsBody: PostSessionsBody,
 signal?: AbortSignal
) => {


      return customInstance<PostSessions200>(
      {url: `/sessions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postSessionsBody, signal
    },
      );
    }



export const getPostSessionsMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postSessions>>, TError,{data: PostSessionsBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postSessions>>, TError,{data: PostSessionsBody}, TContext> => {

const mutationKey = ['postSessions'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postSessions>>, {data: PostSessionsBody}> = (props) => {
          const {data} = props ?? {};

          return  postSessions(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostSessionsMutationResult = NonNullable<Awaited<ReturnType<typeof postSessions>>>
    export type PostSessionsMutationBody = PostSessionsBody
    export type PostSessionsMutationError = void

    /**
 * @summary Authenticate a user
 */
export const usePostSessions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postSessions>>, TError,{data: PostSessionsBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postSessions>>,
        TError,
        {data: PostSessionsBody},
        TContext
      > => {
      return useMutation(getPostSessionsMutationOptions(options), queryClient);
    }

/**
 * @summary Get current authenticated user
 */
export const getMe = (

 signal?: AbortSignal
) => {


      return customInstance<GetMe200>(
      {url: `/me`, method: 'GET', signal
    },
      );
    }




export const getGetMeQueryKey = () => {
    return [
    `/me`
    ] as const;
    }


export const getGetMeQueryOptions = <TData = Awaited<ReturnType<typeof getMe>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({ signal }) => getMe(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>
export type GetMeQueryError = void


export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get current authenticated user
 */

export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Logout current user
 */
export const postLogout = (

 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/logout`, method: 'POST', signal
    },
      );
    }



export const getPostLogoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLogout>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postLogout>>, TError,void, TContext> => {

const mutationKey = ['postLogout'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postLogout>>, void> = () => {


          return  postLogout()
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postLogout>>>

    export type PostLogoutMutationError = unknown

    /**
 * @summary Logout current user
 */
export const usePostLogout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLogout>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postLogout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostLogoutMutationOptions(options), queryClient);
    }

/**
 * @summary Fetch recent questions
 */
export const getQuestions = (
    params?: GetQuestionsParams,
 signal?: AbortSignal
) => {


      return customInstance<QuestionsResponse>(
      {url: `/questions`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetQuestionsQueryKey = (params?: GetQuestionsParams,) => {
    return [
    `/questions`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetQuestionsQueryOptions = <TData = Awaited<ReturnType<typeof getQuestions>>, TError = unknown>(params?: GetQuestionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetQuestionsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getQuestions>>> = ({ signal }) => getQuestions(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getQuestions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQuestionsQueryResult = NonNullable<Awaited<ReturnType<typeof getQuestions>>>
export type GetQuestionsQueryError = unknown


export function useGetQuestions<TData = Awaited<ReturnType<typeof getQuestions>>, TError = unknown>(
 params: undefined |  GetQuestionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestions>>,
          TError,
          Awaited<ReturnType<typeof getQuestions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestions<TData = Awaited<ReturnType<typeof getQuestions>>, TError = unknown>(
 params?: GetQuestionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestions>>,
          TError,
          Awaited<ReturnType<typeof getQuestions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestions<TData = Awaited<ReturnType<typeof getQuestions>>, TError = unknown>(
 params?: GetQuestionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fetch recent questions
 */

export function useGetQuestions<TData = Awaited<ReturnType<typeof getQuestions>>, TError = unknown>(
 params?: GetQuestionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestions>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetQuestionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Create a question
 */
export const postQuestions = (
    postQuestionsBody: PostQuestionsBody,
 signal?: AbortSignal
) => {


      return customInstance<PostQuestions201>(
      {url: `/questions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postQuestionsBody, signal
    },
      );
    }



export const getPostQuestionsMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postQuestions>>, TError,{data: PostQuestionsBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postQuestions>>, TError,{data: PostQuestionsBody}, TContext> => {

const mutationKey = ['postQuestions'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postQuestions>>, {data: PostQuestionsBody}> = (props) => {
          const {data} = props ?? {};

          return  postQuestions(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostQuestionsMutationResult = NonNullable<Awaited<ReturnType<typeof postQuestions>>>
    export type PostQuestionsMutationBody = PostQuestionsBody
    export type PostQuestionsMutationError = void

    /**
 * @summary Create a question
 */
export const usePostQuestions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postQuestions>>, TError,{data: PostQuestionsBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postQuestions>>,
        TError,
        {data: PostQuestionsBody},
        TContext
      > => {
      return useMutation(getPostQuestionsMutationOptions(options), queryClient);
    }

/**
 * @summary Fetch popular questions
 */
export const getQuestionsPopular = (
    params?: GetQuestionsPopularParams,
 signal?: AbortSignal
) => {


      return customInstance<QuestionsResponse>(
      {url: `/questions/popular`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetQuestionsPopularQueryKey = (params?: GetQuestionsPopularParams,) => {
    return [
    `/questions/popular`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetQuestionsPopularQueryOptions = <TData = Awaited<ReturnType<typeof getQuestionsPopular>>, TError = unknown>(params?: GetQuestionsPopularParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionsPopular>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetQuestionsPopularQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getQuestionsPopular>>> = ({ signal }) => getQuestionsPopular(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getQuestionsPopular>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQuestionsPopularQueryResult = NonNullable<Awaited<ReturnType<typeof getQuestionsPopular>>>
export type GetQuestionsPopularQueryError = unknown


export function useGetQuestionsPopular<TData = Awaited<ReturnType<typeof getQuestionsPopular>>, TError = unknown>(
 params: undefined |  GetQuestionsPopularParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionsPopular>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestionsPopular>>,
          TError,
          Awaited<ReturnType<typeof getQuestionsPopular>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestionsPopular<TData = Awaited<ReturnType<typeof getQuestionsPopular>>, TError = unknown>(
 params?: GetQuestionsPopularParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionsPopular>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestionsPopular>>,
          TError,
          Awaited<ReturnType<typeof getQuestionsPopular>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestionsPopular<TData = Awaited<ReturnType<typeof getQuestionsPopular>>, TError = unknown>(
 params?: GetQuestionsPopularParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionsPopular>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fetch popular questions
 */

export function useGetQuestionsPopular<TData = Awaited<ReturnType<typeof getQuestionsPopular>>, TError = unknown>(
 params?: GetQuestionsPopularParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionsPopular>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetQuestionsPopularQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Search questions
 */
export const getQuestionsSearch = (
    params: GetQuestionsSearchParams,
 signal?: AbortSignal
) => {


      return customInstance<QuestionsResponse>(
      {url: `/questions/search`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetQuestionsSearchQueryKey = (params?: GetQuestionsSearchParams,) => {
    return [
    `/questions/search`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetQuestionsSearchQueryOptions = <TData = Awaited<ReturnType<typeof getQuestionsSearch>>, TError = unknown>(params: GetQuestionsSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionsSearch>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetQuestionsSearchQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getQuestionsSearch>>> = ({ signal }) => getQuestionsSearch(params, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getQuestionsSearch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQuestionsSearchQueryResult = NonNullable<Awaited<ReturnType<typeof getQuestionsSearch>>>
export type GetQuestionsSearchQueryError = unknown


export function useGetQuestionsSearch<TData = Awaited<ReturnType<typeof getQuestionsSearch>>, TError = unknown>(
 params: GetQuestionsSearchParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionsSearch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestionsSearch>>,
          TError,
          Awaited<ReturnType<typeof getQuestionsSearch>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestionsSearch<TData = Awaited<ReturnType<typeof getQuestionsSearch>>, TError = unknown>(
 params: GetQuestionsSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionsSearch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestionsSearch>>,
          TError,
          Awaited<ReturnType<typeof getQuestionsSearch>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestionsSearch<TData = Awaited<ReturnType<typeof getQuestionsSearch>>, TError = unknown>(
 params: GetQuestionsSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionsSearch>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search questions
 */

export function useGetQuestionsSearch<TData = Awaited<ReturnType<typeof getQuestionsSearch>>, TError = unknown>(
 params: GetQuestionsSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionsSearch>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetQuestionsSearchQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Get question by slug
 */
export const getQuestionsSlug = (
    slug: string,
 signal?: AbortSignal
) => {


      return customInstance<GetQuestionsSlug200>(
      {url: `/questions/${slug}`, method: 'GET', signal
    },
      );
    }




export const getGetQuestionsSlugQueryKey = (slug: string,) => {
    return [
    `/questions/${slug}`
    ] as const;
    }


export const getGetQuestionsSlugQueryOptions = <TData = Awaited<ReturnType<typeof getQuestionsSlug>>, TError = unknown>(slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionsSlug>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetQuestionsSlugQueryKey(slug);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getQuestionsSlug>>> = ({ signal }) => getQuestionsSlug(slug, signal);





   return  { queryKey, queryFn, enabled: !!(slug), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getQuestionsSlug>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQuestionsSlugQueryResult = NonNullable<Awaited<ReturnType<typeof getQuestionsSlug>>>
export type GetQuestionsSlugQueryError = unknown


export function useGetQuestionsSlug<TData = Awaited<ReturnType<typeof getQuestionsSlug>>, TError = unknown>(
 slug: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionsSlug>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestionsSlug>>,
          TError,
          Awaited<ReturnType<typeof getQuestionsSlug>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestionsSlug<TData = Awaited<ReturnType<typeof getQuestionsSlug>>, TError = unknown>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionsSlug>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestionsSlug>>,
          TError,
          Awaited<ReturnType<typeof getQuestionsSlug>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestionsSlug<TData = Awaited<ReturnType<typeof getQuestionsSlug>>, TError = unknown>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionsSlug>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get question by slug
 */

export function useGetQuestionsSlug<TData = Awaited<ReturnType<typeof getQuestionsSlug>>, TError = unknown>(
 slug: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionsSlug>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetQuestionsSlugQueryOptions(slug,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Edit a question
 */
export const putQuestionsQuestionId = (
    questionId: string,
    putQuestionsQuestionIdBody: PutQuestionsQuestionIdBody,
 signal?: AbortSignal
) => {


      return customInstance<PutQuestionsQuestionId200>(
      {url: `/questions/${questionId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putQuestionsQuestionIdBody, signal
    },
      );
    }



export const getPutQuestionsQuestionIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putQuestionsQuestionId>>, TError,{questionId: string;data: PutQuestionsQuestionIdBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putQuestionsQuestionId>>, TError,{questionId: string;data: PutQuestionsQuestionIdBody}, TContext> => {

const mutationKey = ['putQuestionsQuestionId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putQuestionsQuestionId>>, {questionId: string;data: PutQuestionsQuestionIdBody}> = (props) => {
          const {questionId,data} = props ?? {};

          return  putQuestionsQuestionId(questionId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutQuestionsQuestionIdMutationResult = NonNullable<Awaited<ReturnType<typeof putQuestionsQuestionId>>>
    export type PutQuestionsQuestionIdMutationBody = PutQuestionsQuestionIdBody
    export type PutQuestionsQuestionIdMutationError = unknown

    /**
 * @summary Edit a question
 */
export const usePutQuestionsQuestionId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putQuestionsQuestionId>>, TError,{questionId: string;data: PutQuestionsQuestionIdBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putQuestionsQuestionId>>,
        TError,
        {questionId: string;data: PutQuestionsQuestionIdBody},
        TContext
      > => {
      return useMutation(getPutQuestionsQuestionIdMutationOptions(options), queryClient);
    }

/**
 * @summary Delete a question
 */
export const deleteQuestionsQuestionId = (
    questionId: string,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/questions/${questionId}`, method: 'DELETE', signal
    },
      );
    }



export const getDeleteQuestionsQuestionIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteQuestionsQuestionId>>, TError,{questionId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteQuestionsQuestionId>>, TError,{questionId: string}, TContext> => {

const mutationKey = ['deleteQuestionsQuestionId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteQuestionsQuestionId>>, {questionId: string}> = (props) => {
          const {questionId} = props ?? {};

          return  deleteQuestionsQuestionId(questionId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteQuestionsQuestionIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteQuestionsQuestionId>>>

    export type DeleteQuestionsQuestionIdMutationError = unknown

    /**
 * @summary Delete a question
 */
export const useDeleteQuestionsQuestionId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteQuestionsQuestionId>>, TError,{questionId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteQuestionsQuestionId>>,
        TError,
        {questionId: string},
        TContext
      > => {
      return useMutation(getDeleteQuestionsQuestionIdMutationOptions(options), queryClient);
    }

/**
 * @summary Fetch answers for a question
 */
export const getQuestionsQuestionIdAnswers = (
    questionId: string,
    params?: GetQuestionsQuestionIdAnswersParams,
 signal?: AbortSignal
) => {


      return customInstance<AnswersResponse>(
      {url: `/questions/${questionId}/answers`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetQuestionsQuestionIdAnswersQueryKey = (questionId: string,
    params?: GetQuestionsQuestionIdAnswersParams,) => {
    return [
    `/questions/${questionId}/answers`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetQuestionsQuestionIdAnswersQueryOptions = <TData = Awaited<ReturnType<typeof getQuestionsQuestionIdAnswers>>, TError = unknown>(questionId: string,
    params?: GetQuestionsQuestionIdAnswersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionsQuestionIdAnswers>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetQuestionsQuestionIdAnswersQueryKey(questionId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getQuestionsQuestionIdAnswers>>> = ({ signal }) => getQuestionsQuestionIdAnswers(questionId,params, signal);





   return  { queryKey, queryFn, enabled: !!(questionId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getQuestionsQuestionIdAnswers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQuestionsQuestionIdAnswersQueryResult = NonNullable<Awaited<ReturnType<typeof getQuestionsQuestionIdAnswers>>>
export type GetQuestionsQuestionIdAnswersQueryError = unknown


export function useGetQuestionsQuestionIdAnswers<TData = Awaited<ReturnType<typeof getQuestionsQuestionIdAnswers>>, TError = unknown>(
 questionId: string,
    params: undefined |  GetQuestionsQuestionIdAnswersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionsQuestionIdAnswers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestionsQuestionIdAnswers>>,
          TError,
          Awaited<ReturnType<typeof getQuestionsQuestionIdAnswers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestionsQuestionIdAnswers<TData = Awaited<ReturnType<typeof getQuestionsQuestionIdAnswers>>, TError = unknown>(
 questionId: string,
    params?: GetQuestionsQuestionIdAnswersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionsQuestionIdAnswers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestionsQuestionIdAnswers>>,
          TError,
          Awaited<ReturnType<typeof getQuestionsQuestionIdAnswers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestionsQuestionIdAnswers<TData = Awaited<ReturnType<typeof getQuestionsQuestionIdAnswers>>, TError = unknown>(
 questionId: string,
    params?: GetQuestionsQuestionIdAnswersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionsQuestionIdAnswers>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fetch answers for a question
 */

export function useGetQuestionsQuestionIdAnswers<TData = Awaited<ReturnType<typeof getQuestionsQuestionIdAnswers>>, TError = unknown>(
 questionId: string,
    params?: GetQuestionsQuestionIdAnswersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionsQuestionIdAnswers>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetQuestionsQuestionIdAnswersQueryOptions(questionId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Answer a question
 */
export const postQuestionsQuestionIdAnswers = (
    questionId: string,
    postQuestionsQuestionIdAnswersBody: PostQuestionsQuestionIdAnswersBody,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/questions/${questionId}/answers`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postQuestionsQuestionIdAnswersBody, signal
    },
      );
    }



export const getPostQuestionsQuestionIdAnswersMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postQuestionsQuestionIdAnswers>>, TError,{questionId: string;data: PostQuestionsQuestionIdAnswersBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postQuestionsQuestionIdAnswers>>, TError,{questionId: string;data: PostQuestionsQuestionIdAnswersBody}, TContext> => {

const mutationKey = ['postQuestionsQuestionIdAnswers'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postQuestionsQuestionIdAnswers>>, {questionId: string;data: PostQuestionsQuestionIdAnswersBody}> = (props) => {
          const {questionId,data} = props ?? {};

          return  postQuestionsQuestionIdAnswers(questionId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostQuestionsQuestionIdAnswersMutationResult = NonNullable<Awaited<ReturnType<typeof postQuestionsQuestionIdAnswers>>>
    export type PostQuestionsQuestionIdAnswersMutationBody = PostQuestionsQuestionIdAnswersBody
    export type PostQuestionsQuestionIdAnswersMutationError = void

    /**
 * @summary Answer a question
 */
export const usePostQuestionsQuestionIdAnswers = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postQuestionsQuestionIdAnswers>>, TError,{questionId: string;data: PostQuestionsQuestionIdAnswersBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postQuestionsQuestionIdAnswers>>,
        TError,
        {questionId: string;data: PostQuestionsQuestionIdAnswersBody},
        TContext
      > => {
      return useMutation(getPostQuestionsQuestionIdAnswersMutationOptions(options), queryClient);
    }

/**
 * @summary Mark best answer
 */
export const patchAnswersAnswerIdBest = (
    answerId: string,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/answers/${answerId}/best`, method: 'PATCH', signal
    },
      );
    }



export const getPatchAnswersAnswerIdBestMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAnswersAnswerIdBest>>, TError,{answerId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof patchAnswersAnswerIdBest>>, TError,{answerId: string}, TContext> => {

const mutationKey = ['patchAnswersAnswerIdBest'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchAnswersAnswerIdBest>>, {answerId: string}> = (props) => {
          const {answerId} = props ?? {};

          return  patchAnswersAnswerIdBest(answerId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchAnswersAnswerIdBestMutationResult = NonNullable<Awaited<ReturnType<typeof patchAnswersAnswerIdBest>>>

    export type PatchAnswersAnswerIdBestMutationError = void

    /**
 * @summary Mark best answer
 */
export const usePatchAnswersAnswerIdBest = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchAnswersAnswerIdBest>>, TError,{answerId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchAnswersAnswerIdBest>>,
        TError,
        {answerId: string},
        TContext
      > => {
      return useMutation(getPatchAnswersAnswerIdBestMutationOptions(options), queryClient);
    }

/**
 * @summary Edit an answer
 */
export const putAnswersAnswerId = (
    answerId: string,
    putAnswersAnswerIdBody: PutAnswersAnswerIdBody,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/answers/${answerId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putAnswersAnswerIdBody, signal
    },
      );
    }



export const getPutAnswersAnswerIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putAnswersAnswerId>>, TError,{answerId: string;data: PutAnswersAnswerIdBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putAnswersAnswerId>>, TError,{answerId: string;data: PutAnswersAnswerIdBody}, TContext> => {

const mutationKey = ['putAnswersAnswerId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putAnswersAnswerId>>, {answerId: string;data: PutAnswersAnswerIdBody}> = (props) => {
          const {answerId,data} = props ?? {};

          return  putAnswersAnswerId(answerId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutAnswersAnswerIdMutationResult = NonNullable<Awaited<ReturnType<typeof putAnswersAnswerId>>>
    export type PutAnswersAnswerIdMutationBody = PutAnswersAnswerIdBody
    export type PutAnswersAnswerIdMutationError = unknown

    /**
 * @summary Edit an answer
 */
export const usePutAnswersAnswerId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putAnswersAnswerId>>, TError,{answerId: string;data: PutAnswersAnswerIdBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putAnswersAnswerId>>,
        TError,
        {answerId: string;data: PutAnswersAnswerIdBody},
        TContext
      > => {
      return useMutation(getPutAnswersAnswerIdMutationOptions(options), queryClient);
    }

/**
 * @summary Delete an answer
 */
export const deleteAnswersAnswerId = (
    answerId: string,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/answers/${answerId}`, method: 'DELETE', signal
    },
      );
    }



export const getDeleteAnswersAnswerIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAnswersAnswerId>>, TError,{answerId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteAnswersAnswerId>>, TError,{answerId: string}, TContext> => {

const mutationKey = ['deleteAnswersAnswerId'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAnswersAnswerId>>, {answerId: string}> = (props) => {
          const {answerId} = props ?? {};

          return  deleteAnswersAnswerId(answerId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteAnswersAnswerIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAnswersAnswerId>>>

    export type DeleteAnswersAnswerIdMutationError = unknown

    /**
 * @summary Delete an answer
 */
export const useDeleteAnswersAnswerId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAnswersAnswerId>>, TError,{answerId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAnswersAnswerId>>,
        TError,
        {answerId: string},
        TContext
      > => {
      return useMutation(getDeleteAnswersAnswerIdMutationOptions(options), queryClient);
    }

/**
 * @summary Fetch question comments
 */
export const getQuestionsQuestionIdComments = (
    questionId: string,
    params?: GetQuestionsQuestionIdCommentsParams,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/questions/${questionId}/comments`, method: 'GET',
        params, signal
    },
      );
    }




export const getGetQuestionsQuestionIdCommentsQueryKey = (questionId: string,
    params?: GetQuestionsQuestionIdCommentsParams,) => {
    return [
    `/questions/${questionId}/comments`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetQuestionsQuestionIdCommentsQueryOptions = <TData = Awaited<ReturnType<typeof getQuestionsQuestionIdComments>>, TError = unknown>(questionId: string,
    params?: GetQuestionsQuestionIdCommentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionsQuestionIdComments>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetQuestionsQuestionIdCommentsQueryKey(questionId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getQuestionsQuestionIdComments>>> = ({ signal }) => getQuestionsQuestionIdComments(questionId,params, signal);





   return  { queryKey, queryFn, enabled: !!(questionId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getQuestionsQuestionIdComments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetQuestionsQuestionIdCommentsQueryResult = NonNullable<Awaited<ReturnType<typeof getQuestionsQuestionIdComments>>>
export type GetQuestionsQuestionIdCommentsQueryError = unknown


export function useGetQuestionsQuestionIdComments<TData = Awaited<ReturnType<typeof getQuestionsQuestionIdComments>>, TError = unknown>(
 questionId: string,
    params: undefined |  GetQuestionsQuestionIdCommentsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionsQuestionIdComments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestionsQuestionIdComments>>,
          TError,
          Awaited<ReturnType<typeof getQuestionsQuestionIdComments>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestionsQuestionIdComments<TData = Awaited<ReturnType<typeof getQuestionsQuestionIdComments>>, TError = unknown>(
 questionId: string,
    params?: GetQuestionsQuestionIdCommentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionsQuestionIdComments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getQuestionsQuestionIdComments>>,
          TError,
          Awaited<ReturnType<typeof getQuestionsQuestionIdComments>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetQuestionsQuestionIdComments<TData = Awaited<ReturnType<typeof getQuestionsQuestionIdComments>>, TError = unknown>(
 questionId: string,
    params?: GetQuestionsQuestionIdCommentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionsQuestionIdComments>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fetch question comments
 */

export function useGetQuestionsQuestionIdComments<TData = Awaited<ReturnType<typeof getQuestionsQuestionIdComments>>, TError = unknown>(
 questionId: string,
    params?: GetQuestionsQuestionIdCommentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getQuestionsQuestionIdComments>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetQuestionsQuestionIdCommentsQueryOptions(questionId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}







/**
 * @summary Comment on a question
 */
export const postQuestionsQuestionIdComments = (
    questionId: string,
    postQuestionsQuestionIdCommentsBody: PostQuestionsQuestionIdCommentsBody,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/questions/${questionId}/comments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postQuestionsQuestionIdCommentsBody, signal
    },
      );
    }



export const getPostQuestionsQuestionIdCommentsMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postQuestionsQuestionIdComments>>, TError,{questionId: string;data: PostQuestionsQuestionIdCommentsBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postQuestionsQuestionIdComments>>, TError,{questionId: string;data: PostQuestionsQuestionIdCommentsBody}, TContext> => {

const mutationKey = ['postQuestionsQuestionIdComments'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postQuestionsQuestionIdComments>>, {questionId: string;data: PostQuestionsQuestionIdCommentsBody}> = (props) => {
          const {questionId,data} = props ?? {};

          return  postQuestionsQuestionIdComments(questionId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostQuestionsQuestionIdCommentsMutationResult = NonNullable<Awaited<ReturnType<typeof postQuestionsQuestionIdComments>>>
    export type PostQuestionsQuestionIdCommentsMutationBody = PostQuestionsQuestionIdCommentsBody
    export type PostQuestionsQuestionIdCommentsMutationError = void

    /**
 * @summary Comment on a question
 */
export const usePostQuestionsQuestionIdComments = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postQuestionsQuestionIdComments>>, TError,{questionId: string;data: PostQuestionsQuestionIdCommentsBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postQuestionsQuestionIdComments>>,
        TError,
        {questionId: string;data: PostQuestionsQuestionIdCommentsBody},
        TContext
      > => {
      return useMutation(getPostQuestionsQuestionIdCommentsMutationOptions(options), queryClient);
    }

/**
 * @summary Comment on an answer
 */
export const postAnswersAnswerIdComments = (
    answerId: string,
    postAnswersAnswerIdCommentsBody: PostAnswersAnswerIdCommentsBody,
 signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/answers/${answerId}/comments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAnswersAnswerIdCommentsBody, signal
    },
      );
    }



export const getPostAnswersAnswerIdCommentsMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAnswersAnswerIdComments>>, TError,{answerId: string;data: PostAnswersAnswerIdCommentsBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postAnswersAnswerIdComments>>, TError,{answerId: string;data: PostAnswersAnswerIdCommentsBody}, TContext> => {

const mutationKey = ['postAnswersAnswerIdComments'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAnswersAnswerIdComments>>, {answerId: string;data: PostAnswersAnswerIdCommentsBody}> = (props) => {
          const {answerId,data} = props ?? {};

          return  postAnswersAnswerIdComments(answerId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAnswersAnswerIdCommentsMutationResult = NonNullable<Awaited<ReturnType<typeof postAnswersAnswerIdComments>>>
    export type PostAnswersAnswerIdCommentsMutationBody = PostAnswersAnswerIdCommentsBody
    export type PostAnswersAnswerIdCommentsMutationError = void

    /**
 * @summary Comment on an answer
 */
export const usePostAnswersAnswerIdComments = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAnswersAnswerIdComments>>, TError,{answerId: string;data: PostAnswersAnswerIdCommentsBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAnswersAnswerIdComments>>,
        TError,
        {answerId: string;data: PostAnswersAnswerIdCommentsBody},
        TContext
      > => {
      return useMutation(getPostAnswersAnswerIdCommentsMutationOptions(options), queryClient);
    }

/**
 * @summary Health check
 */
export const getHealth = (

 signal?: AbortSignal
) => {


      return customInstance<GetHealth200>(
      {url: `/health`, method: 'GET', signal
    },
      );
    }




export const getGetHealthQueryKey = () => {
    return [
    `/health`
    ] as const;
    }


export const getGetHealthQueryOptions = <TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHealthQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHealth>>> = ({ signal }) => getHealth(signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHealthQueryResult = NonNullable<Awaited<ReturnType<typeof getHealth>>>
export type GetHealthQueryError = unknown


export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealth>>,
          TError,
          Awaited<ReturnType<typeof getHealth>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealth>>,
          TError,
          Awaited<ReturnType<typeof getHealth>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Health check
 */

export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetHealthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
